name: Build Style Dictionary

on:
  workflow_dispatch:            # ↩ puedes lanzarlo a mano
  push:                         # ↩ o cada vez que cambien tokens/ o la config
    paths:
      - "tokens/**"
      - "config.json"
      - ".github/workflows/build-style-dictionary.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo
      - uses: actions/checkout@v4

      # 2) Node 18 (igual que los otros workflows)
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3) Instala dependencias
      - name: Install dependencies
        run: npm ci

      # 4) (Debug) Lista todos los JSON encontrados
      - name: List token files
        run: |
          echo "Archivos en tokens/ detectados por find:"
          find tokens -type f -name '*.json' -print

      # 5) Limpia los alias "$" — script ya corregido
      - name: Remove dollar signs
        run: |
          chmod +x removedollarsigns.sh
          ./removedollarsigns.sh

      # 6) Build Style Dictionary (log en modo info)
      - name: Build Style Dictionary
        run: |
          SD_LOG_LEVEL=info npm run build

      # 7) Sube la carpeta build/ como artefacto
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: style-dictionary-build
          path: build/
