name: Sync Figma variables to tokens (JSON-only)

on:
  workflow_dispatch:
    inputs:
      file_key:
        description: Figma FILE_KEY a sincronizar
        required: true

jobs:
  sync-figma-to-tokens:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      # 1) Checkout & Node
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci            # usa package-lock

      # 2) Pull: Figma → tokens/
      - name: Sync Figma variables → tokens
        run: npm run sync-figma-to-tokens -- --output tokens
        env:
          FILE_KEY: ${{ inputs.file_key }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_ACTION_VARIABLES_SYNC_FIGMA_TOKEN }}

      # 3) Normaliza alias ($)      ─ opcional pero recomendable
      - name: Remove dollar signs
        run: |
          chmod +x removedollarsigns.sh
          ./removedollarsigns.sh

      # 4) PR sólo con carpeta tokens/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(tokens): update from Figma"
          title: "Update design tokens from Figma"
          body: |
            Tokens actualizados automáticamente desde:
            https://www.figma.com/file/${{ inputs.file_key }}
          branch: update-tokens-json-only
          add-paths: |
            tokens/**
